#!/usr/bin/env python3
"""first_run_setup.py — Auto-configure Vessence on first launch.

Detects which AI CLI is installed (claude/gemini/codex) and sets up the
.env file accordingly. Asks the user only for things that can't be auto-detected.

Usage:
    python startup_code/first_run_setup.py
"""

import os
import shutil
import sys
from pathlib import Path

VESSENCE_HOME = Path(__file__).resolve().parents[1]
VESSENCE_DATA_HOME = Path(os.environ.get("VESSENCE_DATA_HOME", str(VESSENCE_HOME.parent / "vessence-data")))
ENV_FILE = VESSENCE_DATA_HOME / ".env"


def detect_cli_provider() -> tuple[str | None, str | None]:
    """Detect which AI CLI is installed.

    Returns (provider, cli_path) tuple.
    Provider is one of: claude, gemini, openai, or None if none found.
    """
    # Check for Claude CLI (Claude Code)
    claude_path = shutil.which("claude")
    if claude_path:
        return "claude", claude_path
    # Check for Gemini CLI
    gemini_path = shutil.which("gemini")
    if gemini_path:
        return "gemini", gemini_path
    # Check for Codex CLI (OpenAI)
    codex_path = shutil.which("codex")
    if codex_path:
        return "openai", codex_path
    return None, None


def read_env() -> dict[str, str]:
    """Read existing .env file into a dict."""
    env: dict[str, str] = {}
    if not ENV_FILE.exists():
        return env
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        env[key.strip()] = val.strip()
    return env


def write_env(env: dict[str, str], merge: bool = True) -> None:
    """Write env vars to .env, optionally merging with existing."""
    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    if merge:
        existing = read_env()
        existing.update(env)
        env = existing
    lines = ["# Vessence runtime environment", "# Auto-generated by first_run_setup.py", ""]
    for key, val in env.items():
        lines.append(f"{key}={val}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"  → Updated {ENV_FILE}")


def ask(prompt: str, default: str = "", required: bool = False) -> str:
    """Prompt user for input with optional default."""
    while True:
        suffix = f" [{default}]" if default else (" (required)" if required else " (optional)")
        val = input(f"{prompt}{suffix}: ").strip()
        if val:
            return val
        if default:
            return default
        if not required:
            return ""
        print("  This value is required.")


def main():
    print("=" * 60)
    print("Vessence First-Run Setup")
    print("=" * 60)
    print()

    existing_env = read_env()
    new_env: dict[str, str] = {}

    # ── Step 1: Detect AI CLI ──
    print("Step 1: Detecting AI CLI provider...")
    provider, cli_path = detect_cli_provider()
    if provider:
        print(f"  ✓ Found {provider} CLI at {cli_path}")
        new_env["JANE_BRAIN"] = provider
        if provider == "claude":
            new_env["CLAUDE_BIN"] = cli_path
        elif provider == "gemini":
            new_env["GEMINI_BIN"] = cli_path
        elif provider == "openai":
            new_env["CODEX_BIN"] = cli_path
        print(f"  → JANE_BRAIN={provider}")
    else:
        print("  ✗ No AI CLI found in PATH")
        print()
        print("  Vessence needs one of:")
        print("    - claude (Claude Code) — https://docs.claude.com/claude-code")
        print("    - gemini (Gemini CLI)  — https://github.com/google-gemini/gemini-cli")
        print("    - codex  (Codex CLI)   — https://github.com/openai/codex")
        print()
        manual = ask("Install one of the above and re-run, OR enter the path manually now")
        if manual:
            new_env["CLAUDE_BIN"] = manual
            new_env["JANE_BRAIN"] = "claude"
        else:
            print("  Aborting setup. Install a CLI and re-run.")
            return 1

    print()

    # ── Step 2: User identity ──
    print("Step 2: Your identity")
    user_name = existing_env.get("USER_NAME") or ask("Your name", default="User")
    new_env["USER_NAME"] = user_name
    print()

    # ── Step 3: Optional Google OAuth (for multi-device access) ──
    print("Step 3: Google sign-in (optional)")
    print("  Skip this if you only access Jane locally on your computer.")
    print("  Set this up if you want to use Jane from other devices (phone, tablet).")
    print()
    enable_google = ask("Enable Google sign-in? (y/N)", default="N").lower().startswith("y")
    if enable_google:
        new_env["GOOGLE_CLIENT_ID"] = ask("  Google Client ID", required=True)
        new_env["GOOGLE_CLIENT_SECRET"] = ask("  Google Client Secret", required=True)
        email = ask("  Your Google email", required=True)
        new_env["ALLOWED_GOOGLE_EMAILS"] = email
        # Generate session secret
        import secrets
        new_env["SESSION_SECRET_KEY"] = secrets.token_hex(32)
    print()

    # ── Step 4: Optional weather location ──
    print("Step 4: Weather location (optional)")
    if existing_env.get("WEATHER_LAT"):
        print(f"  ✓ Already set: {existing_env.get('WEATHER_LOCATION', 'unknown')}")
    else:
        loc = ask("  City, State (e.g., 'Boston, MA') — or skip")
        if loc:
            new_env["WEATHER_LOCATION"] = loc
    print()

    # ── Step 5: Write .env ──
    print("Step 5: Writing configuration...")
    write_env(new_env, merge=True)
    print()
    print("=" * 60)
    print("Setup complete!")
    print("=" * 60)
    print()
    print("Next steps:")
    print(f"  1. Start the server: systemctl --user start jane-web.service")
    print(f"  2. Open Jane: http://localhost:8081/")
    print(f"  3. If you enabled Google sign-in, sign in at /auth/google")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
