#!/usr/bin/env python3
"""first_run_setup.py — Auto-configure Vessence on first launch.

Detects which AI CLI is installed (claude/gemini/codex) and sets up the
.env file accordingly. Asks the user only for things that can't be auto-detected.

Usage:
    python startup_code/first_run_setup.py
"""

import os
import shutil
import sys
from pathlib import Path

VESSENCE_HOME = Path(__file__).resolve().parents[1]
VESSENCE_DATA_HOME = Path(os.environ.get("VESSENCE_DATA_HOME", str(VESSENCE_HOME.parent / "vessence-data")))
ENV_FILE = VESSENCE_DATA_HOME / ".env"


def detect_cli_provider() -> tuple[str | None, str | None]:
    """Detect which AI CLI is installed.

    Returns (provider, cli_path) tuple.
    Provider is one of: claude, gemini, openai, or None if none found.
    """
    # Check for Claude CLI (Claude Code)
    claude_path = shutil.which("claude")
    if claude_path:
        return "claude", claude_path
    # Check for Gemini CLI
    gemini_path = shutil.which("gemini")
    if gemini_path:
        return "gemini", gemini_path
    # Check for Codex CLI (OpenAI)
    codex_path = shutil.which("codex")
    if codex_path:
        return "openai", codex_path
    return None, None


def read_env() -> dict[str, str]:
    """Read existing .env file into a dict."""
    env: dict[str, str] = {}
    if not ENV_FILE.exists():
        return env
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        env[key.strip()] = val.strip()
    return env


def write_env(env: dict[str, str], merge: bool = True) -> None:
    """Write env vars to .env, optionally merging with existing."""
    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    if merge:
        existing = read_env()
        existing.update(env)
        env = existing
    lines = ["# Vessence runtime environment", "# Auto-generated by first_run_setup.py", ""]
    for key, val in env.items():
        lines.append(f"{key}={val}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"  → Updated {ENV_FILE}")


def open_browser(url: str) -> None:
    """Open a URL in the user's default browser. Silently fails on headless systems."""
    try:
        import webbrowser
        webbrowser.open(url)
    except Exception:
        pass


def guide_google_oauth_setup(env: dict) -> None:
    """Walk the user through Google OAuth setup step-by-step.

    Explains why each step matters and opens browser tabs to the right pages.
    Validates inputs and re-prompts on bad values.
    """
    print()
    print("─" * 60)
    print("  GOOGLE SIGN-IN SETUP — Why we need this")
    print("─" * 60)
    print()
    print("  When you access Jane from your phone or another device, the server")
    print("  needs to know it's really YOU and not a stranger who guessed your URL.")
    print()
    print("  Google sign-in is the easiest way: you click 'Sign in with Google',")
    print("  Google verifies your identity, and tells the server 'yes, this is")
    print("  the right person.' No passwords to remember, no extra accounts.")
    print()
    print("  This requires creating a free Google Cloud project (5 minutes).")
    print("  I'll walk you through every step.")
    print()
    input("  Press Enter to continue... ")
    print()

    print("─" * 60)
    print("  STEP 1: Create a Google Cloud project")
    print("─" * 60)
    print()
    print("  Opening: https://console.cloud.google.com/projectcreate")
    print()
    print("  In the page that opens:")
    print("    1. Project name: 'Vessence' (or anything you like)")
    print("    2. Click CREATE")
    print("    3. Wait ~10 seconds for the project to be created")
    print("    4. Make sure the new project is selected at the top of the page")
    print()
    open_browser("https://console.cloud.google.com/projectcreate")
    input("  Press Enter when done... ")
    print()

    print("─" * 60)
    print("  STEP 2: Configure the OAuth consent screen")
    print("─" * 60)
    print()
    print("  This is what users see when they sign in — name of your app, etc.")
    print()
    print("  Opening: https://console.cloud.google.com/apis/credentials/consent")
    print()
    print("  In the page that opens:")
    print("    1. User Type: External → CREATE")
    print("    2. App name: 'Vessence Jane' (or anything)")
    print("    3. User support email: your email")
    print("    4. Developer contact: your email")
    print("    5. Click SAVE AND CONTINUE through Scopes (skip — leave defaults)")
    print("    6. Test users: ADD USERS → enter your email → SAVE AND CONTINUE")
    print("    7. Click BACK TO DASHBOARD")
    print()
    open_browser("https://console.cloud.google.com/apis/credentials/consent")
    input("  Press Enter when done... ")
    print()

    print("─" * 60)
    print("  STEP 3: Create OAuth credentials")
    print("─" * 60)
    print()
    print("  Now we'll create the actual Client ID and Secret.")
    print()
    print("  Opening: https://console.cloud.google.com/apis/credentials")
    print()
    print("  In the page that opens:")
    print("    1. Click + CREATE CREDENTIALS at the top → OAuth client ID")
    print("    2. Application type: Web application")
    print("    3. Name: 'Vessence Web' (or anything)")
    print()
    print("    4. Authorized redirect URIs — click ADD URI and add:")
    print("       http://localhost:8081/auth/google/callback")
    print("       (also add your remote URL if you have one, e.g.:")
    print("        https://YOUR_DOMAIN.vessences.com/auth/google/callback)")
    print()
    print("    5. Click CREATE")
    print("    6. A popup shows your Client ID and Client Secret — KEEP IT OPEN")
    print()
    open_browser("https://console.cloud.google.com/apis/credentials")
    input("  Press Enter when the popup is showing... ")
    print()

    print("─" * 60)
    print("  STEP 4: Paste your credentials below")
    print("─" * 60)
    print()
    while True:
        client_id = ask("  Client ID (ends with .apps.googleusercontent.com)", required=True)
        if ".apps.googleusercontent.com" in client_id:
            break
        print("  ⚠ That doesn't look right. Client ID ends with .apps.googleusercontent.com")
    client_secret = ask("  Client Secret (starts with GOCSPX-)", required=True)
    print()
    email = ask("  Your Google email (the one allowed to sign in)", required=True)
    print()

    env["GOOGLE_CLIENT_ID"] = client_id
    env["GOOGLE_CLIENT_SECRET"] = client_secret
    env["ALLOWED_GOOGLE_EMAILS"] = email
    import secrets
    env["SESSION_SECRET_KEY"] = secrets.token_hex(32)

    print("─" * 60)
    print("  ✓ Google sign-in configured!")
    print("─" * 60)
    print()
    print("  After the server starts, sign in at:")
    print("    http://localhost:8081/auth/google")
    print()


def ask(prompt: str, default: str = "", required: bool = False) -> str:
    """Prompt user for input with optional default."""
    while True:
        suffix = f" [{default}]" if default else (" (required)" if required else " (optional)")
        val = input(f"{prompt}{suffix}: ").strip()
        if val:
            return val
        if default:
            return default
        if not required:
            return ""
        print("  This value is required.")


def main():
    print("=" * 60)
    print("Vessence First-Run Setup")
    print("=" * 60)
    print()

    existing_env = read_env()
    new_env: dict[str, str] = {}

    # ── Step 1: Detect AI CLI ──
    print("Step 1: Detecting AI CLI provider...")
    provider, cli_path = detect_cli_provider()
    if provider:
        print(f"  ✓ Found {provider} CLI at {cli_path}")
        new_env["JANE_BRAIN"] = provider
        if provider == "claude":
            new_env["CLAUDE_BIN"] = cli_path
        elif provider == "gemini":
            new_env["GEMINI_BIN"] = cli_path
        elif provider == "openai":
            new_env["CODEX_BIN"] = cli_path
        print(f"  → JANE_BRAIN={provider}")
    else:
        print("  ✗ No AI CLI found in PATH")
        print()
        print("  Vessence needs one of:")
        print("    - claude (Claude Code) — https://docs.claude.com/claude-code")
        print("    - gemini (Gemini CLI)  — https://github.com/google-gemini/gemini-cli")
        print("    - codex  (Codex CLI)   — https://github.com/openai/codex")
        print()
        manual = ask("Install one of the above and re-run, OR enter the path manually now")
        if manual:
            new_env["CLAUDE_BIN"] = manual
            new_env["JANE_BRAIN"] = "claude"
        else:
            print("  Aborting setup. Install a CLI and re-run.")
            return 1

    print()

    # ── Step 2: User identity ──
    print("Step 2: Your identity")
    user_name = existing_env.get("USER_NAME") or ask("Your name", default="User")
    new_env["USER_NAME"] = user_name
    print()

    # ── Step 3: Choose access mode ──
    print("Step 3: How do you want to access Jane?")
    print()
    print("  [1] Local only — chat with Jane on this computer at http://localhost:8081")
    print("      (no setup needed, no auth required for localhost)")
    print()
    print("  [2] Remote access — use Jane from your phone, tablet, or other devices")
    print("      Requires:")
    print("        - A permanent URL to reach your server (e.g., chieh.vessences.com)")
    print("        - Google sign-in to verify it's you")
    print()
    print("      The easiest way: create a free Vessences account at")
    print("      https://vessences.com/signup — you get a permanent subdomain")
    print("      and the relay handles the networking automatically.")
    print()
    print("      Alternative: set up your own Cloudflare tunnel pointing at localhost:8081")
    print("      (more technical — see docs/cloudflare-tunnel.md)")
    print()
    access_mode = ask("Choose [1] or [2]", default="1")

    if access_mode == "2":
        guide_google_oauth_setup(new_env)
    print()

    # ── Step 4: Optional weather location ──
    print("Step 4: Weather location (optional)")
    if existing_env.get("WEATHER_LAT"):
        print(f"  ✓ Already set: {existing_env.get('WEATHER_LOCATION', 'unknown')}")
    else:
        loc = ask("  City, State (e.g., 'Boston, MA') — or skip")
        if loc:
            new_env["WEATHER_LOCATION"] = loc
    print()

    # ── Step 5: Write .env ──
    print("Step 5: Writing configuration...")
    write_env(new_env, merge=True)
    print()
    print("=" * 60)
    print("Setup complete!")
    print("=" * 60)
    print()
    print("Next steps:")
    print(f"  1. Start the server: systemctl --user start jane-web.service")
    print(f"     (on macOS: launchctl load ~/Library/LaunchAgents/jane-web.plist)")
    print(f"  2. Open Jane: http://localhost:8081/")
    if access_mode == "2":
        print(f"  3. Sign in with Google at http://localhost:8081/auth/google")
        print(f"  4. Set up your tunnel/relay so YOUR_DOMAIN points at localhost:8081")
        print(f"     - Easiest: https://vessences.com/signup (free relay)")
        print(f"     - Or: Cloudflare tunnel pointing at localhost:8081")
    else:
        print(f"  3. To enable remote access later, re-run this script")
    print()
    print("Optional: Gmail integration")
    print(f"  pip install -r requirements-optional.txt")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
