#!/usr/bin/env python3
import ast
from pathlib import Path


TEST_DIR = Path("/home/chieh/ambient/vessence/test_code")
OUTPUT = TEST_DIR / "TESTS.md"


def classify(name: str) -> str:
    lower = name.lower()
    if lower.startswith("benchmark_"):
        return "benchmark"
    if lower.startswith("debug") or lower.startswith("reproduce_"):
        return "debug"
    if lower.startswith("check_") or "health" in lower or lower.startswith("list_") or lower.startswith("discover_"):
        return "inspection"
    if lower.startswith("test_"):
        return "test"
    return "artifact"


def extract_summary(path: Path) -> str:
    if path.suffix != ".py":
        return "Non-Python artifact."
    try:
        source = path.read_text(encoding="utf-8", errors="replace")
        module = ast.parse(source)
        doc = ast.get_docstring(module)
        if doc:
            return " ".join(doc.strip().splitlines()).strip()
    except Exception:
        pass

    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            text = stripped.lstrip("#").strip()
            if text:
                return text
        if stripped:
            break
    return "No inline description found."


def runnable(path: Path) -> str:
    if path.suffix == ".py":
        return f"`/home/chieh/google-adk-env/adk-venv/bin/python {path}`"
    return "N/A"


def main() -> None:
    files = sorted(p for p in TEST_DIR.iterdir() if p.is_file())
    rows = []
    for path in files:
        if path.name == "TESTS.md":
            continue
        kind = classify(path.name)
        rows.append({
            "name": path.name,
            "kind": kind,
            "summary": extract_summary(path),
            "command": runnable(path),
        })

    lines = [
        "# Test Registry",
        "",
        "Autogenerated from `/home/chieh/ambient/vessence/test_code`.",
        "This is the current source of truth for ad hoc tests, debug scripts, inspections, and benchmarks.",
        "",
        "| File | Type | Summary | Run |",
        "| --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| `{row['name']}` | `{row['kind']}` | {row['summary'].replace('|', '\\|')} | {row['command'].replace('|', '\\|')} |"
        )

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(str(OUTPUT))


if __name__ == "__main__":
    main()
