"""Quick acknowledgement selection for Jane proxy."""

from __future__ import annotations

import random
from collections.abc import Callable, Sequence
from dataclasses import dataclass


@dataclass(frozen=True)
class _AckRule:
    patterns: tuple[str, ...]
    options: tuple[str, ...]
    startswith: bool = False


def _choose(options: Sequence[str], chooser: Callable[[Sequence[str]], str] | None) -> str:
    return (chooser or random.choice)(options)


def _matches_rule(msg: str, rule: _AckRule) -> bool:
    if rule.startswith:
        return msg.startswith(rule.patterns)
    return any(pattern in msg for pattern in rule.patterns)


_ACK_RULES = (
    _AckRule(
        patterns=(
            "is ",
            "are ",
            "was ",
            "were ",
            "do ",
            "does ",
            "did ",
            "can ",
            "could ",
            "will ",
            "would ",
            "should ",
            "how ",
            "what ",
            "where ",
            "when ",
            "why ",
            "who ",
            "have you",
            "has ",
            "which ",
        ),
        options=(
            "Let me check.",
            "Good question — looking into it.",
            "Let me look into that.",
            "Checking now.",
            "Hmm, let me find out.",
            "One sec, let me see.",
            "Let me pull that up.",
            "Give me a moment to check.",
            "Interesting question — looking into it.",
            "Let me think about that.",
            "Let me take a look.",
            "Digging into it now.",
            "Hold on, checking.",
            "Let me look that up.",
            "Good one — let me see.",
            "Ooh, good question. Let me check.",
            "One sec — I know this one... or I will in a moment.",
            "Let me look into that real quick.",
            "Give me a sec, I'll dig that up.",
            "Let me poke around and find out.",
            "That's a good one. Checking now.",
            "Hold that thought — checking.",
            "Curious about that too, actually. Let me check.",
            "I should know this... let me verify.",
            "Let me take a peek.",
            "Hmm, good question. Digging in.",
            "Fair question — checking now.",
            "One moment while I track that down.",
        ),
        startswith=True,
    ),
    _AckRule(
        patterns=(
            "status",
            "progress",
            "update",
            "how's it going",
            "what's happening",
            "working on",
            "where are we",
            "current state",
            "what happened",
        ),
        options=(
            "Let me check on that.",
            "One sec, pulling up the status.",
            "Checking the current state.",
            "Let me see where things stand.",
            "Pulling up the details now.",
            "Let me get you caught up.",
            "Checking what's happened.",
            "Give me a sec to review.",
            "One sec — pulling up the latest.",
            "Let me see what's been going on.",
            "Ah, good timing — let me review.",
            "Hold on, let me see where we left off.",
            "Let me take stock real quick.",
        ),
    ),
    _AckRule(
        patterns=(
            "fix",
            "bug",
            "broken",
            "error",
            "crash",
            "wrong",
            "doesn't work",
            "not working",
            "failed",
            "failing",
            "issue",
            "problem",
        ),
        options=(
            "On it — let me investigate.",
            "Looking into it now.",
            "Let me dig into this.",
            "I'll take a look at what's going on.",
            "Let me trace through this.",
            "Investigating now.",
            "Let me figure out what happened.",
            "On it — give me a moment.",
            "Let me hunt this down.",
            "Diving into the logs now.",
            "I see — let me look into it.",
            "Let me check what went wrong.",
            "Ugh, let me see what happened.",
            "On it — detective mode activated.",
            "Alright, let's figure this out.",
            "Time to put on the debugging hat.",
            "Let me take a look under the hood.",
            "Hmm, that's not right. Let me investigate.",
            "Ok, let's track this down.",
            "I'll get to the bottom of this.",
            "On the case. Give me a moment.",
            "Something's off — let me look.",
            "Alright, diving in.",
        ),
    ),
    _AckRule(
        patterns=(
            "think",
            "opinion",
            "suggest",
            "recommend",
            "advice",
            "better",
            "prefer",
            "thoughts on",
            "feel about",
            "makes sense",
            "good idea",
        ),
        options=(
            "Let me think about that.",
            "Good question — let me consider the options.",
            "Hmm, let me weigh in on that.",
            "Let me think this through.",
            "Interesting — give me a sec to think.",
            "Let me consider that.",
            "Hmm, let me think on that.",
            "Let me chew on that for a moment.",
            "Interesting angle. Let me consider...",
            "Let me weigh the options real quick.",
            "That's worth thinking about. One sec.",
            "Hmm, I have thoughts. Let me organize them.",
            "Good point — let me consider that.",
            "Let me mull that over for a sec.",
        ),
    ),
    _AckRule(
        patterns=(
            "explain",
            "tell me about",
            "what is",
            "what's a",
            "how does",
            "why does",
            "meaning of",
            "difference between",
        ),
        options=(
            "Sure, let me explain.",
            "Good question — here's the deal.",
            "Let me break that down.",
            "Here's how it works.",
            "Let me walk you through it.",
            "Alright, let me explain that.",
            "Oh, this is a fun one. Let me explain.",
            "Sure thing — here's the rundown.",
            "Let me break that down for you.",
            "Alright, storytime. Kind of.",
            "So basically, here's what's going on.",
            "Let me lay it out.",
            "Happy to explain — here goes.",
            "This is a good one to know. Let me explain.",
        ),
    ),
    _AckRule(
        patterns=(
            "hello",
            "hey",
            "hi ",
            "good morning",
            "good evening",
            "good night",
            "what's up",
            "sup",
            "yo",
        ),
        options=(
            "Hey!",
            "Hi there!",
            "Hey, what's up?",
            "Hey!",
            "What's up?",
            "Hi! What can I help with?",
            "Hey! Good to hear from you.",
            "Hey! What's on your mind?",
            "Hi! Ready when you are.",
            "Hey there! What are we working on?",
            "Yo! What's the plan?",
            "Hi! What's cooking?",
            "Hey! Fire away.",
        ),
    ),
    _AckRule(
        patterns=(
            "thank",
            "thanks",
            "appreciate",
            "nice work",
            "good job",
            "well done",
            "awesome",
            "great job",
            "perfect",
        ),
        options=(
            "Glad to help!",
            "Anytime!",
            "Happy to help.",
            "No problem!",
            "Of course!",
            "You got it.",
            "Glad that worked out!",
            "No sweat!",
            "That's what I'm here for.",
            "Teamwork!",
            "We make a good team.",
            "Appreciate you saying that!",
            "Always happy to help.",
        ),
    ),
    _AckRule(
        patterns=(
            "show me",
            "list ",
            "display",
            "print",
            "give me",
            "pull up",
            "let me see",
        ),
        options=(
            "Sure, pulling that up.",
            "One moment.",
            "Let me get that for you.",
            "Coming right up.",
            "Sure thing.",
            "On it.",
            "Grabbing that now.",
            "Pulling it up now.",
            "On it — here you go in a sec.",
            "Sure thing, just a moment.",
            "Let me fetch that.",
            "Right away.",
            "Give me a sec to pull that together.",
        ),
    ),
    _AckRule(
        patterns=(
            "build",
            "deploy",
            "create",
            "make",
            "set up",
            "install",
            "add ",
            "implement",
            "write",
        ),
        options=(
            "On it.",
            "Let me get that set up.",
            "Building now.",
            "Working on it.",
            "Sure — putting that together.",
            "Alright, let me build that out.",
            "Let me handle that.",
            "Starting on it now.",
            "Sure, let me set that up.",
            "Got it — getting started.",
            "On it!",
            "Let's build this.",
            "Rolling up my sleeves. Let's go.",
            "Consider it started.",
            "Building time. On it.",
            "Sure — let me wire that up.",
            "Alright, let's make it happen.",
            "Let me cook something up.",
            "Time to build. Let's go.",
        ),
    ),
    _AckRule(
        patterns=(
            "remove",
            "delete",
            "clean up",
            "get rid of",
            "drop",
        ),
        options=(
            "Got it — cleaning that up.",
            "Removing it now.",
            "On it.",
            "Sure, taking care of that.",
            "Let me handle that.",
            "Got it — cleaning house.",
            "Gone in a sec.",
            "Consider it gone.",
            "Sweeping that away now.",
            "On it — poof.",
        ),
    ),
    _AckRule(
        patterns=(
            "again",
            "still",
            "keeps",
            "annoying",
            "frustrated",
            "seriously",
            "come on",
            "ugh",
            "wtf",
        ),
        options=(
            "I hear you. Let me take another look.",
            "Sorry about that — let me fix this properly.",
            "Understood. Let me dig deeper this time.",
            "Fair. Let me get this right.",
            "Yeah, that's not great. On it.",
            "Let me approach this differently.",
            "I got you — let me sort this out.",
        ),
    ),
)


def pick_ack(user_message: str, *, chooser: Callable[[Sequence[str]], str] | None = None) -> str | None:
    """Pick a context-appropriate quick ack based on the user's message."""

    msg = (user_message or "").lower().strip()

    for rule in _ACK_RULES:
        if _matches_rule(msg, rule):
            return _choose(rule.options, chooser)

    return None
