"""DELEGATE_OPUS — complex, ambiguous, or multi-step requests."""

CLASS_NAME = "DELEGATE_OPUS"
NEEDS_LLM = False

EXAMPLES = [
    "call my wife", "call john", "phone my mom",
    "fix the auth bug", "debug this issue",
    "why is the playlist empty", "why isn't this working",
    "what's going on with the server", "look into the crash",
    "help me write an email", "draft a message to the team",
    "what do you think I should do", "give me advice on this",
    "explain how this works", "can you research this",
    "set a timer for 10 minutes", "set an alarm for 7am",
    "create a calendar event", "add a meeting tomorrow",
    "what's the traffic like", "how long to get to work",
    "order me some food", "order pizza",
    "book a restaurant", "make a reservation",
    "look up flights to New York", "search for hotels",
    "read me the news", "what's happening in the world",
    "tell me about the latest AI news",
    "remind me at 5pm", "set a reminder",
    "open my calendar", "what's on my schedule",
    "check my appointments", "what do I have today",
    "translate this document", "summarize this article",
    "write a poem about spring", "write a birthday message",
    "help me plan my week", "what should I make for dinner",
    "find a recipe for pasta", "how do I fix this error",
    "what's the best route", "navigate to work",
    "turn on the lights", "set the thermostat",
    "play the game", "launch the app",
    "update my status", "post something",
    # Reminders to self (NOT send messages to others)
    "can you remind me to take my pills at 8pm",
    "remind me to call the dentist tomorrow",
    "please remind me about the meeting at 3pm",
    "remind me to pick up groceries",
    "can you remind me to check the oven",
    # Meta questions about music/songs (debugging, not playing)
    "can you check why there were no songs in the music player",
    "why are no songs loading in the player",
    "the music player is not working",
    "why isn't it picking up my playlists",
    "I feel like the music player is broken",
    "the songs are not playing correctly",
    "why can't it find any songs",
    # Meta questions about email/Gmail access
    "currently do you have access to my Gmail",
    "do you have access to my email",
    "are you connected to my Gmail",
    "can you access my email account",
    "is your Gmail integration working",
    "do you have email permissions",
    # "email" mentioned but NOT an email request (project/architecture discussion)
    "each user should have their own email address",
    "we should separate each user's memory and each user's email",
    "I want to organize things based on email address",
    "different users should have different email configurations",
    "each user's unique email address should be the identifier",
    "the email field in the user profile",
    "how does email authentication work in the codebase",
    # Meta questions about message storage/sync status
    "do we have a copy of the text messages on the server",
    "are the messages stored on the server",
    "how many messages are stored in the database",
    "are the text messages backed up",
    "is the message database up to date",
    "can you show me the context the AI gets for each message",
    "what context does the model get for each message",
    "show me what Gemma sees for each conversation",
    # Meta questions about code and systems
    "how is our current weather report coded up",
    "how is the weather feature implemented",
    "why is the weather request taking so long",
    "can you do a benchmark on the weather API",
    "why is the app not syncing with the server",
    "read the log files to see what the Android app is doing",
    "check the Android logs to see what is happening",
    "look at the logs to debug the sync issue",
    # Talking about music but not requesting playback
    "I feel like Gemma is not doing a good job picking up playlists",
    "the playlist detection is not working well",
    "why is it not finding the right songs in my playlist",
    # Weather mentioned but NOT a weather request
    "Nice weather we're having, huh.",
    "Ugh, I hate this cold.", "The weather's been crazy lately.",
    "My grandpa used to predict weather by his knee.",
    "light frizzles a little bit of rain",
    "it's raining cats and dogs out there",
    "the weather is beautiful today isn't it",
    "can you do a benchmark to explain to me why currently if I ask for the weather it just takes so long",
    "how does the weather cron job work in the codebase",
    "how does the weather cron job run in this codebase",
    "how is our weather feature implemented",
    # "sync" mentioned but NOT about message sync
    "How does Python asyncio event loop work?",
    "How does Python's asyncio event loop work?",
    "How does Python asyncio work?",
    "we are out of sync again in terms of the conversation",
    "please look into the conversation sync problem",
    "the front end and back end are out of sync",
    "can you sync up the code changes",
    # "messages/texts" mentioned but NOT about reading texts
    "at this point do we have a copy of the text messages on the server or is it empty",
    "So currently you have my text messages stored on the Local Host right",
    "I'm talking about messages that are just there I'm not talking about the unread ones",
    "yes and I want you to read the log files to see what the Android app is doing",
    "I would like you to read the last 3 turns in Jane web",
    "how many from last yesterday",
    # Generic affirmatives that need context (NOT send message)
    "yeah please", "yes please", "yeah please do that",
    "ok do it", "go ahead", "sure", "yep", "alright",
    "yes please flip that on", "yeah that's fine",
    "ok sounds good", "okay sounds good",
    # Questions about contacts/people (NOT sending a message)
    "do you have the contact information for my wife",
    "do you have to contact information for my wife",
    "what's my wife's phone number", "who is in my contacts",
    # Cooking/recipes (NOT shopping list)
    "How do I make pancakes?", "how do I cook pasta",
    "what's a good recipe for lasagna", "how do you bake bread",
    # Talking about messages conceptually (NOT read/send)
    "how many from last yesterday",
    "I'm talking about messages that are just there I'm not talking about the unread ones",
    "how is the message system working",
    "are the messages being stored correctly",
    # Server/system management (NOT message sync)
    "restart the server", "please restart the server",
    "restart jane", "restart the web server",
    "restart the server with opus", "I want opus to restart the server",
    "please use opus brain and restart the server",
    "reboot the server", "can you restart the service",
    "restart jane web", "do a server restart",
    "restart the jane service", "bring the server back up",
    "kill and restart the server", "bounce the server",
    # Ambiguous "play" / "let's" (NOT music play)
    "let's play", "let's do it", "let's go", "let's get started",
    "I need to think about that for now let's",
    "let's move on", "let's talk about something else",
    "let's work on the next thing", "let's switch topics",
    "for now let's focus on something else",
    # Ambient project goals — explicitly escalate to Stage 3, NOT the
    # fast TODO_LIST handler. Ambient is a planning/strategy topic.
    "what are my ambient project goals",
    "tell me about the ambient project",
    "what's the status of the ambient project",
    "what's next for the ambient project",
    "how's the ambient project going",
    "what am I doing on the ambient project this week",
    "what am I working on for ambient",
    "what's pending on ambient",
    "remind me of the ambient project plan",
    # Non-TODO "lists" that look TODO-ish but aren't — wish list, reading
    # list, music list, etc. These must NOT hit TODO_LIST.
    "what's on my wish list",
    "read me my wish list",
    "what's on my reading list",
    "what books are on my reading list",
    "what's on my bucket list",
    "what's on my music list",
    "what's on my packing list",
    # TODO-edit phrasings (add/remove/strike) — read-only TODO_LIST
    # handler must NOT swallow these. They escalate to Stage 3.
    "add clean the garage to my todo list",
    "add clean the garage to my todo",
    "add clean the kitchen to my todo",
    "add buy a gift to my todo list",
    "add a new todo item for tomorrow",
    "put call the plumber on my todo list",
    "put call the plumber on my list",
    "put get the oil changed on my todo",
    "remove the dentist from my todo",
    "remove the dentist task from my todo list",
    "cross off the clinic errand from my todo",
    "strike the recommendation letter off my to-do",
    "mark the clinic task as done",
    "mark the clinic errand complete",
    "I already did the clinic errand",
    "I already did the clinic task",
    "I already did the errand at the clinic",
    "I already finished the clinic",
    "I finished my recommendation letter",
    "I finished the student recommendation letter",
    "I already finished that todo item",
    "I already crossed that off my todo",
    "write me a todo item for later",
    "write a todo item for tomorrow",
    "write a new todo for later",
    "draft me a new todo item",
    "compose a new todo",
    "make a todo for me to follow up on that",
    "create a new todo item",
    "create a todo for calling the plumber",
    # Venting / conversational chatter that mentions tasks
    "I have a lot of tasks today, want to vent about it",
    "I have a ton of tasks today want to talk about it",
    "I got so many tasks today, feeling stressed",
    "too many tasks today, let me vent",
    "I'm overwhelmed with my todo list can we talk",
    "I'm overwhelmed by my tasks want to chat",
    "my to-do is stressing me out",
    "my todo list is way too long help me prioritize",
    # "Todo" used in meta/self-improvement context — not the user's list
    "what did you fix overnight on your own todo",
    "what's on your internal todo",
    "what's left on jane's todo",
    # Text-contact phrasing that happens to mention the clinic — these
    # are ambiguous (who-to-text inquiries), so let Stage 3 decide.
    "who should I text at the clinic today",
    "who at the clinic should I text today",
    "who do I need to text at the clinic",
    "which client at the clinic should I contact",
    "which clinic person should I text",
    "should I text someone at the clinic",
    "who at the clinic needs a text",
    # Status updates after the user did something outside Jane. These are
    # not commands to send a new SMS and not conversation-ending phrases.
    "ok sent it",
    "ok, sent it",
    "okay sent it",
    "I sent it",
    "sent it",
    "done, I sent it",
    "ok I sent that",
    "I already sent it",
    "I just sent the message",
]

CONTEXT = None
