"""Prompt templates for transcript quality review jobs."""
from __future__ import annotations

from pathlib import Path


CODEX_PROMPT_TEMPLATE = """\
You are a quality auditor for "Jane", a 3-stage AI voice assistant pipeline.

The pipeline works like this:
  Stage 1 (Gemma classifier): classifies the user's intent into a category
    (timer, greeting, send message, weather, etc.) with a confidence score.
  Stage 2 (handler): a deterministic handler for that category processes the
    request directly (fast path). If it can't handle it, it escalates.
  Stage 3 (configured frontier brain): full LLM brain handles complex/ambiguous requests.

There is also a pending_action_resolver that runs BEFORE Stage 1: if the
previous turn left a follow-up question pending (Stage 2 or Stage 3), the
next user reply is routed directly to the right handler, bypassing classification.

Below are transcripts and logs from one day of real conversations.

Your job — evaluate EACH STAGE for every turn:

1. **Stage 1 accuracy**: Was the classification correct? Did the user say
   "set a timer" but get classified as "others"? Did "read my messages"
   get classified as "greeting"? Check the `stage1_classifier` log lines.

2. **Stage 2 correctness**: Did the handler produce the right response?
   Did the timer handler parse the duration correctly? Did the SMS handler
   resolve the right contact? Check `timer handler`, `resolver`, handler log lines.

3. **Stage 3 quality**: When Opus handled the turn, was the reply helpful
   and correct? Did Opus hallucinate a tool it doesn't have? Did it promise
   something it can't deliver? Did it set the right tool markers?

4. **Client-side execution**: Did the Android client execute the tool
   correctly? Did STT relaunch? Did the timer actually fire? Check
   android diagnostic events (tool_handler, voice_flow).

5. **Follow-up flow**: When a pending_action was set, did the resolver
   route the next turn correctly? Did the conversation flow naturally?

For each issue found, trace the logs to explain the ROOT CAUSE.
Rate: CRITICAL (user-facing breakage), MEDIUM (degraded UX), LOW (minor).

Output format — emit ONLY a JSON array, no markdown fences, no commentary:

[
  {{
    "turn_time": "2026-04-15 HH:MM:SS",
    "user_msg_snippet": "first 80 chars of user message",
    "issue": "brief description of what went wrong",
    "root_cause": "what the logs reveal about why",
    "severity": "CRITICAL|MEDIUM|LOW",
    "suggested_fix": "concrete code change suggestion",
    "relevant_log_lines": ["line1", "line2"]
  }}
]

If no issues found, return an empty array: []

--- BEGIN TRANSCRIPT + LOGS ---

{context}

--- END TRANSCRIPT + LOGS ---
"""


FRONTIER_FIX_PROMPT_TEMPLATE = """\
You are Jane's self-improvement system. The following report was generated by
Codex after reviewing today's conversation transcripts. For each issue:

1. READ the issue description and root cause.
2. VALIDATE: check whether the issue is real by reading the relevant source code.
   If the issue is a false positive (Codex misunderstood), skip it and note why.
3. FIX: for valid issues, implement the smallest correct code change.
4. TEST: write a unit test (in test_code/) that verifies the fix works and
   doesn't break existing functionality. Run the test to confirm it passes.
5. After all fixes, append a "## Fixes Applied" section to the report at
   {report_path} summarizing what you changed.

IMPORTANT:
- Acquire the code edit lock before modifying files:
  python agent_skills/code_lock.py status  (check first)
  Then use the lock context manager in your edits.
- Only fix issues rated CRITICAL or MEDIUM. Log LOW issues but skip fixing.
- Do NOT restart the server — the nightly job runner handles that.
- If you can't fix an issue, document why in the report.

PIPELINE ARCHITECTURE — DO NOT CHANGE:
The intent pipeline has a fixed, intentional structure:
    chroma (embedding top-K) → classifier LLM (qwen) → Stage 2 handler → Stage 3 (Opus)
When fixing misclassifications, your fix MUST stay WITHIN this structure.
The correct tools for a misclassified turn are, in priority order:
  1. Add/adjust exemplars in intent_classifier/v2/classes/<class>.py so
     chroma pulls the right class into the top-K.
  2. Improve the class's description/example list in
     jane_web/jane_v2/classes/<class>/metadata.py so qwen picks it.
  3. Tune chroma distance thresholds (e.g. JANE_V3_STAGE2_MAX_DISTANCE)
     when a wrong class's exemplars are winning on distance.
  4. Fix output-parsing bugs in intent_classifier/v3/classifier.py
     (e.g. label normalization — stripping brackets/underscores).
  5. Improve the Stage 2 handler itself (emit pending context, handle
     follow-ups) or the Stage 3 escalation path.
FORBIDDEN:
  - Do NOT add regex/keyword "fast paths" in the classifier that bypass
    chroma+qwen. One-off lexical short-circuits duplicate chroma's job
    and create two sources of truth that drift. The only exception
    already in the tree is a narrow output-parsing guard (e.g. the
    delete-intent post-validation demote); do not add new ones without
    Chieh's explicit approval.
  - Do NOT add new classifier stages, new pre-classifiers, or new
    routers. If a turn is misrouted, the fix is in the data
    (exemplars/descriptions) or the existing stage, not a new shortcut.

EXEMPLAR SPECIFICITY — MANDATORY when adding to chroma:
Every exemplar you add to intent_classifier/v2/classes/<class>.py MUST
contain wording that is specific to that class (its signature noun or
verb). Generic phrasings that could plausibly belong to another class
or to general conversational speech are FORBIDDEN — they pollute chroma
and hijack unrelated turns.
  - GOOD (clinic): "how many patients do I have today" — "patients" anchors it.
  - BAD  (clinic): "how busy is she on Monday" — no clinic-specific noun;
                    could match any schedule/calendar class.
  - BAD  (clinic): "who's coming in today" — hijacks any turn with "coming in".
  - BAD  (clinic): "what about Tuesday" — pure weekday; would hijack every
                    turn that mentions a day. Short topical follow-ups
                    like this belong in a Stage 2 handler's
                    STAGE2_FOLLOWUP pending_action, NOT in chroma.
Rule of thumb: if removing the class's signature noun still leaves a
sensible English sentence, the exemplar is too generic — reword it or
drop it.

Report contents:

{report_content}
"""

# Backward-compatible name used by the existing runner.
CLAUDE_FIX_PROMPT_TEMPLATE = FRONTIER_FIX_PROMPT_TEMPLATE


def build_codex_review_prompt(context: str) -> str:
    return CODEX_PROMPT_TEMPLATE.format(context=context)


def build_frontier_fix_prompt(report_path: str | Path, report_content: str) -> str:
    return FRONTIER_FIX_PROMPT_TEMPLATE.format(
        report_path=report_path,
        report_content=report_content,
    )
